######################################################################
# Automatically generated by qmake (2.01a) Thu May 12 22:32:45 2011
######################################################################

TEMPLATE = app
TARGET = StudInfo
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += FormMain.h DataAccess.h
FORMS += formMain.ui
SOURCES += FormMain.cpp DataAccess.cpp main.cpp
